import { z } from 'zod'

export const ParameterValueSchema = z.enum([
	'boolean',
	'boolean_digit',
	'buildingNumber',
	'card_expiration',
	'card_number',
	'card_type',
	'city',
	'company_name',
	'counter',
	'country',
	'countryCode',
	'date',
	'dateTime',
	'ean',
	'email',
	'firstName',
	'first_name',
	'image',
	'lastName',
	'latitude',
	'longText',
	'longitude',
	'name',
	'null',
	'number',
	'phone',
	'pokemon',
	'postcode',
	'state',
	'streetAddress',
	'streetName',
	'text',
	'upc',
	'uuid',
	'vat',
	'website',
	'word',
])

export const User = z.object({
	company: z.string(),
	country: z.string(),
	state: z.string(),
	city: z.string(),
	zipcode: z.string(),
	employees: z.number(),
	revenue: z.number(),
	website: z.string().url(),
	sales_rep: z.string(),
	last_contacted: z.string(),
	purchased: z.boolean(),
	notes: z.string(),
})

export const CustomApiSchema = z.object({
	status: z.string(),
	code: z.number(),
	locale: z.string(),
	seed: z.string().nullable(),
	total: z.number(),
	data: z.array(User),
})
